# Generated by Django 2.1.5 on 2019-01-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.TextField(max_length=2)),
                ('_class', models.CharField(max_length=30)),
            ],
        ),
    ]
